language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Vlasov_All_Lab
  - make -j
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
notifications:
  email: false
